(cl:defpackage Mocap-srv
  (:use )
  (:export
   "MOCAP_GETMOCAPFRAME"
   "<MOCAP_GETMOCAPFRAME-REQUEST>"
   "MOCAP_GETMOCAPFRAME-REQUEST"
   "<MOCAP_GETMOCAPFRAME-RESPONSE>"
   "MOCAP_GETMOCAPFRAME-RESPONSE"
   "MOCAP_GETMOCAPTRANSFORMATION"
   "<MOCAP_GETMOCAPTRANSFORMATION-REQUEST>"
   "MOCAP_GETMOCAPTRANSFORMATION-REQUEST"
   "<MOCAP_GETMOCAPTRANSFORMATION-RESPONSE>"
   "MOCAP_GETMOCAPTRANSFORMATION-RESPONSE"
   "MOCAP_SETMOCAPTRANSFORMATION"
   "<MOCAP_SETMOCAPTRANSFORMATION-REQUEST>"
   "MOCAP_SETMOCAPTRANSFORMATION-REQUEST"
   "<MOCAP_SETMOCAPTRANSFORMATION-RESPONSE>"
   "MOCAP_SETMOCAPTRANSFORMATION-RESPONSE"
   "MOCAP_SETOBJTRANSFORMATION"
   "<MOCAP_SETOBJTRANSFORMATION-REQUEST>"
   "MOCAP_SETOBJTRANSFORMATION-REQUEST"
   "<MOCAP_SETOBJTRANSFORMATION-RESPONSE>"
   "MOCAP_SETOBJTRANSFORMATION-RESPONSE"
  ))

