/* Auto-generated by genmsg_cpp for file /home/jiaji/TestNatNet/Mocap/srv/mocap_GetMocapTransformation.srv */
#ifndef MOCAP_SERVICE_MOCAP_GETMOCAPTRANSFORMATION_H
#define MOCAP_SERVICE_MOCAP_GETMOCAPTRANSFORMATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace Mocap
{
template <class ContainerAllocator>
struct mocap_GetMocapTransformationRequest_ {
  typedef mocap_GetMocapTransformationRequest_<ContainerAllocator> Type;

  mocap_GetMocapTransformationRequest_()
  {
  }

  mocap_GetMocapTransformationRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct mocap_GetMocapTransformationRequest
typedef  ::Mocap::mocap_GetMocapTransformationRequest_<std::allocator<void> > mocap_GetMocapTransformationRequest;

typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationRequest> mocap_GetMocapTransformationRequestPtr;
typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationRequest const> mocap_GetMocapTransformationRequestConstPtr;


template <class ContainerAllocator>
struct mocap_GetMocapTransformationResponse_ {
  typedef mocap_GetMocapTransformationResponse_<ContainerAllocator> Type;

  mocap_GetMocapTransformationResponse_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , q0(0.0)
  , qx(0.0)
  , qy(0.0)
  , qz(0.0)
  , ret(0)
  , msg()
  {
  }

  mocap_GetMocapTransformationResponse_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , q0(0.0)
  , qx(0.0)
  , qy(0.0)
  , qz(0.0)
  , ret(0)
  , msg(_alloc)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _q0_type;
  double q0;

  typedef double _qx_type;
  double qx;

  typedef double _qy_type;
  double qy;

  typedef double _qz_type;
  double qz;

  typedef int64_t _ret_type;
  int64_t ret;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  msg;


  typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct mocap_GetMocapTransformationResponse
typedef  ::Mocap::mocap_GetMocapTransformationResponse_<std::allocator<void> > mocap_GetMocapTransformationResponse;

typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationResponse> mocap_GetMocapTransformationResponsePtr;
typedef boost::shared_ptr< ::Mocap::mocap_GetMocapTransformationResponse const> mocap_GetMocapTransformationResponseConstPtr;

struct mocap_GetMocapTransformation
{

typedef mocap_GetMocapTransformationRequest Request;
typedef mocap_GetMocapTransformationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct mocap_GetMocapTransformation
} // namespace Mocap

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Mocap/mocap_GetMocapTransformationRequest";
  }

  static const char* value(const  ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const  ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3f432c2b24231bfa1982c3d95599d931";
  }

  static const char* value(const  ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3f432c2b24231bfaULL;
  static const uint64_t static_value2 = 0x1982c3d95599d931ULL;
};

template<class ContainerAllocator>
struct DataType< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Mocap/mocap_GetMocapTransformationResponse";
  }

  static const char* value(const  ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 q0\n\
float64 qx\n\
float64 qy\n\
float64 qz\n\
int64 ret\n\
string msg\n\
\n\
\n\
";
  }

  static const char* value(const  ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct mocap_GetMocapTransformationRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.q0);
    stream.next(m.qx);
    stream.next(m.qy);
    stream.next(m.qz);
    stream.next(m.ret);
    stream.next(m.msg);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct mocap_GetMocapTransformationResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<Mocap::mocap_GetMocapTransformation> {
  static const char* value() 
  {
    return "3f432c2b24231bfa1982c3d95599d931";
  }

  static const char* value(const Mocap::mocap_GetMocapTransformation&) { return value(); } 
};

template<>
struct DataType<Mocap::mocap_GetMocapTransformation> {
  static const char* value() 
  {
    return "Mocap/mocap_GetMocapTransformation";
  }

  static const char* value(const Mocap::mocap_GetMocapTransformation&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3f432c2b24231bfa1982c3d95599d931";
  }

  static const char* value(const Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Mocap/mocap_GetMocapTransformation";
  }

  static const char* value(const Mocap::mocap_GetMocapTransformationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3f432c2b24231bfa1982c3d95599d931";
  }

  static const char* value(const Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Mocap/mocap_GetMocapTransformation";
  }

  static const char* value(const Mocap::mocap_GetMocapTransformationResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MOCAP_SERVICE_MOCAP_GETMOCAPTRANSFORMATION_H

